export const sortPipeTestMockGoods = [{
  id: '0',
  name: 'Холодильник с морозильником Beko CSMV5335MC0S',
  imageUrls: [],
  availableAmount: 4,
  price: 999.0,
  rating: 4,
  description: '',
},
{
  id: '1',
  name: 'Мотоцикл Хонда',
  imageUrls: [],
  availableAmount: 5,
  price: 769.0,
  rating: 2,
  description: '',
},
{
  id: 'RCSK310M20S',
  name: 'Компьютер стационарный домашний',
  imageUrls: [],
  availableAmount: 10,
  price: 612.0,
  rating: 1,
  description: '',
},
{
  id: '33',
  name: 'Автомат Калашникова',
  imageUrls: [],
  availableAmount: 9,
  price: 809,
  rating: 3,
  description: '',
},
{
  id: 'LGGAB419SQJL',
  name: 'Телевизор LG',
  imageUrls: [],
  availableAmount: 12,
  price: 1480,
  rating: 5,
  description: '',
}];

export const sortPipeTestMockGoodsResultByAscendingPrice = [{
  id: 'RCSK310M20S',
  name: 'Компьютер стационарный домашний',
  imageUrls: [],
  availableAmount: 10,
  price: 612.0,
  rating: 1,
  description: '',
},
{
  id: '1',
  name: 'Мотоцикл Хонда',
  imageUrls: [],
  availableAmount: 5,
  price: 769.0,
  rating: 2,
  description: '',
},
{
  id: '33',
  name: 'Автомат Калашникова',
  imageUrls: [],
  availableAmount: 9,
  price: 809,
  rating: 3,
  description: '',
},
{
  id: '0',
  name: 'Холодильник с морозильником Beko CSMV5335MC0S',
  imageUrls: [],
  availableAmount: 4,
  price: 999.0,
  rating: 4,
  description: '',
},
{
  id: 'LGGAB419SQJL',
  name: 'Телевизор LG',
  imageUrls: [],
  availableAmount: 12,
  price: 1480,
  rating: 5,
  description: '',
}];

export const sortPipeTestMockGoodsResultByAscendingRating = [{
  id: 'RCSK310M20S',
  name: 'Компьютер стационарный домашний',
  imageUrls: [],
  availableAmount: 10,
  price: 612.0,
  rating: 1,
  description: '',
},
{
  id: '1',
  name: 'Мотоцикл Хонда',
  imageUrls: [],
  availableAmount: 5,
  price: 769.0,
  rating: 2,
  description: '',
},
{
  id: '33',
  name: 'Автомат Калашникова',
  imageUrls: [],
  availableAmount: 9,
  price: 809,
  rating: 3,
  description: '',
},
{
  id: '0',
  name: 'Холодильник с морозильником Beko CSMV5335MC0S',
  imageUrls: [],
  availableAmount: 4,
  price: 999.0,
  rating: 4,
  description: '',
},
{
  id: 'LGGAB419SQJL',
  name: 'Телевизор LG',
  imageUrls: [],
  availableAmount: 12,
  price: 1480,
  rating: 5,
  description: '',
}];

export const sortPipeTestMockGoodsResultByAscendingAmount = [{
  id: '0',
  name: 'Холодильник с морозильником Beko CSMV5335MC0S',
  imageUrls: [],
  availableAmount: 4,
  price: 999.0,
  rating: 4,
  description: '',
},
{
  id: '1',
  name: 'Мотоцикл Хонда',
  imageUrls: [],
  availableAmount: 5,
  price: 769.0,
  rating: 2,
  description: '',
},
{
  id: '33',
  name: 'Автомат Калашникова',
  imageUrls: [],
  availableAmount: 9,
  price: 809,
  rating: 3,
  description: '',
},
{
  id: 'RCSK310M20S',
  name: 'Компьютер стационарный домашний',
  imageUrls: [],
  availableAmount: 10,
  price: 612.0,
  rating: 1,
  description: '',
},
{
  id: 'LGGAB419SQJL',
  name: 'Телевизор LG',
  imageUrls: [],
  availableAmount: 12,
  price: 1480,
  rating: 5,
  description: '',
}];
